import json

def create_prompt(question: str, schema: str) -> str:
    """Creates a Structured Chain-of-Thought (SCoT) prompt."""
    
    # The reasoning structure should ideally be generated by an LLM in a few-shot example,
    # but for the final prompt, we just provide the structure to be filled.
    reasoning_structure = {
        "Task": "Generate SQL query from natural language question.",
        "Question": question,
        "Database Schema": "Provided above.",
        "Structured Reasoning": {
            "Step 1": "Identify relevant tables and their join conditions.",
            "Step 2": "Formulate the subquery or condition for the first constraint ('Math' course).",
            "Step 3": "Formulate the subquery or condition for the second constraint ('Physics' course).",
            "Step 4": "Combine the conditions to find the intersection of students.",
            "Step 5": "Construct the final SELECT statement to retrieve the student names."
        },
        "Output Format": "A single, executable SQL query.",
        "Final SQL": "" # The LLM fills this part
    }
    
    # We convert the JSON structure to a string for the prompt
    reasoning_str = json.dumps(reasoning_structure, indent=2)

    prompt = f"""{schema}
Follow the structured reasoning process below to generate the final SQL query.

{reasoning_str}
"""
    return prompt